
export enum MutationTypes {
    SET_PAIR_MATRIX = 'SET_PAIR_MATRIX',
    SET_USER_LIST = 'SET_USER_LIST',
    SET_SELECTED_PAIR_LIST = 'SET_SELECTED_PAIR_LIST',
    SET_USER_PAIR_SETS = 'SET_USER_PAIR_SETS'
}